import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin('./i18n/request.ts');

/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    // Static export: srcset entries point at variants pre-generated by
    // scripts/optimize-photos.mjs. Together these lists must equal PHOTO_WIDTHS
    // in lib/photo-loader.ts, or the srcset gets duplicate files.
    loader: 'custom',
    loaderFile: './lib/photo-loader.ts',
    deviceSizes: [640, 960, 1280, 1920],
    imageSizes: [256, 400],
  },
  output: 'export',
  trailingSlash: true,
}

export default withNextIntl(nextConfig)
