import type { Metadata } from "next"
import { routing } from "@/i18n/routing"

export const SITE_URL = "https://hydrastudios.se"

/** Absolute URL for a path on the site. Paths end in "/" to match `trailingSlash: true`. */
export function siteUrl(path = "/"): string {
  return `${SITE_URL}${path}`
}

/**
 * Path of a page in a locale. Swedish lives at the site root (/, /blogg/), the
 * other locales under their prefix (/en/, /en/blogg/).
 */
export function localePath(locale: string, path = "/"): string {
  return locale === routing.defaultLocale ? path : `/${locale}${path}`
}

/** hreflang map for a path that exists in every locale, e.g. "/". */
export function languageAlternates(path = "/"): Record<string, string> {
  const languages: Record<string, string> = {}
  for (const locale of routing.locales) {
    languages[locale] = siteUrl(localePath(locale, path))
  }
  languages["x-default"] = siteUrl(path)
  return languages
}

// Google picks the search result favicon from the home page, so every page
// (including the root redirect page) links the same set. Files are generated by
// scripts/generate-icons.mjs.
export const ICONS: Metadata["icons"] = {
  icon: [
    { url: "/favicon.ico", sizes: "48x48" },
    { url: "/favicon.svg", type: "image/svg+xml" },
    { url: "/icon-48.png", sizes: "48x48", type: "image/png" },
    { url: "/icon-96.png", sizes: "96x96", type: "image/png" },
    { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
  ],
  apple: [{ url: "/icon-180.png", sizes: "180x180" }],
  other: [{ rel: "mask-icon", url: "/favicon.svg", color: "#556B2F" }],
}

export const OG_IMAGE = { url: "/images/og-image.jpg", width: 1200, height: 630 }

export const LOGO_URL = siteUrl("/images/png/hydra-logo-full-texture-original@2.png")

export const OG_LOCALES: Record<string, string> = {
  sv: "sv_SE",
  en: "en_US",
  de: "de_DE",
  ja: "ja_JP",
  ko: "ko_KR",
}

/** Stable id so the studio, website and blog posts refer to the same entity in JSON-LD. */
export const STUDIO_ID = siteUrl("/#studio")

// Shown on the site and in the Google Business Profile; keep the two identical.
export const PHONE_DISPLAY = "070-748 52 94"
export const PHONE_E164 = "+46707485294"
